### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.NativeModules.RNExitApp.exitApp') exitApp

### ISSUE THREAD

**Issue by ajangi** [wumke/react-native-exit-app#13]
I'm getting this error when I'm using this library! Would you please help me to solve it?

**Comment by ajangi** [comment]
![image](https://user-images.githubusercontent.com/18447056/39749840-edb707a8-52c8-11e8-83ea-d1183a0e3a1a.png)

**Comment by wumke** [comment]
Could it be that the module is not correctly linked in the native project code? That is mostly the reason I've seen myself with native libraries...

**Comment by ajangi** [comment]
I solved it myself! Thanks!

**Comment by hsunami10** [comment]
@ajangi how'd you solve it? I'm getting a similar error with RNExitApp being undefined

**Comment by Bokoa** [comment]
> I solved it myself! Thanks!

@ajangi how did you solve the error?

**Comment by erycson** [comment]
> I solved it myself! Thanks!

@ajangi how'd you solve the error?

**Comment by imrealashu** [comment]
@ajangi how'd you solve the error?
