### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by b-asaf** [wumke/react-native-exit-app#17]
Hi @wumke ,

Is there any change/depiction regarding the license?
In issue  #3 this was raised, but I see that the license file was not change/update since the initial commit.
Are there any updates?

Thanks

**Comment by wumke** [comment]
There has not been a new release yet... I'm changing all my repos to MIT in next releases, that would allow all users to use the libraries in their projects.

**Comment by matthieucan** [comment]
Hi @wumke,
Thank you very much for this lib, it works like a charm.
Do you have an idea of when you will do a next release with the MIT license?
Thanks in advance!

**Comment by hpelitebook745G2** [comment]
@wumke are there any updates? I'd like to add your nice library in my production app next week. So far I'm liking its purpose.

**Comment by vincenzovitale** [comment]
Same here, without a change in the licence we cannot use your library.

Thanks,
V.

**Comment by wumke** [comment]
On vacation for 2 weeks now... will update when i'm back

**Comment by assafb81** [comment]
@wumke, any updates about the license?

**Comment by wumke** [comment]
whoops totally forgotten to merge... done now, use latest commit instead of npm version
