### ISSUE TITLE
Error with react-native@0.56

### ISSUE THREAD

**Issue by Ashoat** [wumke/react-native-exit-app#18]
The project won't build with RN 0.56. `react-native run-android` crashes with the following error:

```
/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/ashoat/Dropbox/src/squadcal/native/node_modules/react-native-exit-app/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
```

**Comment by Ashoat** [comment]
I was able to get around this by updating `node_modules/react-native-exit-app/android/build.gradle` to the following:

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 2
        versionName "1.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    compile 'com.facebook.react:react-native:+'
}
```

Let me know if you'd like me to submit a PR updating this file.

**Comment by wumke** [comment]
So it's the compileSdkVersion and buildToolVersion you have changed if i'm correct? 

See https://github.com/wumke/react-native-exit-app/pull/16 for a even better solution that should be used by all libraries if you'd ask me! (I will implement it in all next releases and new libraries...)

**Comment by km16** [comment]
Facing the same issue. Looking forward to the next release.

**Comment by km16** [comment]
Can you please publish the next release soon? 
Every time I do a npm install, I would have to edit the build.gradle file.

**Comment by wumke** [comment]
I think that existing modules with correct version will not get overwritten by following npm install commands, but not sure... 
I'm very busy at the moment.

Anyway, my golden tip: also commit the node_modules directory in your project repository, that way you can prevent failing builds due to dependency project deletion (yes, some people do this kind of things without warning!) and also make small changes to dependency projects that are project specific for your own project. 
I'm moving away from getting dependencies from the internet each time for all production projects, which allows me to deploy code from a private repository without internet access being required.

**Comment by DanielBoening** [comment]
@wumke Its quite some time that you gave the tip to check in your node_modules. Do you still do it? Did it turn out to be less hastle or did you encounter problems? I'm curious as I had thought about that as well but didn't do it yet.

**Comment by wumke** [comment]
For me it is simple, for long running projects I always scrape together all you need for building your app and add it to git... the only disadvantage is the additional space you use (but hey, how much does a GB on simple HD cost these days?). 
Once I had had used a libary in an experimental project, 2 years later I needed it and that library was deleted by the owner... luckily I had the project in working condition on an old spare laptop or I could start over from scratch! 
You can almost think of it as an assurance: as long as everything goes as planned you don't need it... but when it goes wrong you are happy you invested in it and would be screwed if didn't! :-)

**Comment by DanielBoening** [comment]
Thanks a lot for the fast answer. It does sound logically, as it really is not worth the talking if you need some more GB on the server. I'll consider changing this for my project as well soon.
