### ISSUE TITLE
cannot read property "exitApp" of undefined

### ISSUE THREAD

**Issue by hsunami10** [wumke/react-native-exit-app#21]
Why is importing RNExitApp giving me undefined for both iOS and Android? I installed and linked correctly for both.

**Comment by SurajMDurgad** [comment]
I found a solution that worked for me, try uninstalling and reinstalling the package.
Code :
`react-native unlink react-native-exit-app`
`react-native uninstall react-native-exit-app`
`npm install react-native-exit-app --save`

**Comment by wumke** [comment]
Sometimes the react native flow gets messed up... reinstalling modules, cleaning the packager cache, cleaning native project cache... all these thing might help and should be the first thing to do in case of troubles.
