### ISSUE TITLE
Execution failed for task ':react-native-exit-app:verifyReleaseResources'.

### ISSUE THREAD

**Issue by fanam** [wumke/react-native-exit-app#24]
An error happened while generating apk file using './gradlew assembleRelease' command.

App perfectly exits when tested using a virtual machine.

![capturea](https://user-images.githubusercontent.com/11724218/50219569-ac86f380-03b5-11e9-967b-bd2edfd8e820.JPG)

**Comment by autotrof** [comment]
i get message that too

**Comment by wumke** [comment]
I've not seen this one myself yet, did you try getting more info out of the logs? --stacktrace or --debug, as the logs tell us.
Anyone found more clues or possible reasons for the error or solutions?

(Also I see you use windows, which I've never used to develop Android apps.)

**Comment by Samykills** [comment]
Hi,

Those still having this issue, check https://github.com/wumke/react-native-exit-app/pull/25

**Comment by vitormomberg** [comment]
I have the same problem, the #25 work for me

**Comment by kpratik2015** [comment]
Not sure why this still hasn't been merged. It prevented me from making a build.

**Comment by wumke** [comment]
merged now (I'm to busy at the moment and forgot to merge!)... use latest github commit instead of npm version to get latest changes.
