### ISSUE TITLE
podspec file missing from npm package

### ISSUE THREAD

**Issue by jsamr** [wumke/react-native-exit-app#26]
![image](https://user-images.githubusercontent.com/3646758/54355480-7f1ab080-4659-11e9-80a0-368a55cbcf95.png)

**Comment by wumke** [comment]
I have never seen this issue with any package...
What were you doing when it went wrong?
What exactly goes wrong?
What is the suggested fix?

**Comment by jsamr** [comment]
`react-native link` [now checks for podspec files at the root of npm modules if you are using it in your project](https://facebook.github.io/react-native/docs/linking-libraries-ios#step-2). However, it is not published in your npm package. You just need to publish a new version making sure [react-native-exit-app.podspec](https://github.com/wumke/react-native-exit-app/blob/master/react-native-exit-app.podspec) is included :slightly_smiling_face:

**Comment by wumke** [comment]
Aha, that's probably why I've never seen this myself: 'If you are using a Podfile'...
So you can use the version directly from github for now?

(Will be included in next publish!)

**Comment by jsamr** [comment]
@wumke That's what I'm doing and it works :-)
