### ISSUE TITLE
Android gradle change compile to implementation

### ISSUE THREAD

**Issue by tamirrab** [wumke/react-native-exit-app#27]
Android gradle change compile to implementation

**Comment by wumke** [comment]
Will be included in next release...

**Comment by kristoferpelchat** [comment]
@wumke Any timeframes on the next release? I could use this fix. Thanks in advance!

**Comment by wumke** [comment]
I'll try to find some time later this week... very busy at work and at home at the moment!

**Comment by wumke** [comment]
done by mergin pull request
