### ISSUE TITLE
react-native link doesnt add Package

### ISSUE THREAD

**Issue by henry132109** [wumke/react-native-exit-app#29]
In MainApplication.java, `new RNExitAppPackage()` still has to be added manually despite using `react-native link react-native-exit-app`

react-native-cli: 2.0.1
react-native: 0.58.6
react-native-exit-app: 1.0.0
I'm also using Wix's react-native-navigation 2.21.1 and [MainApplication.java file was modified](https://wix.github.io/react-native-navigation/#/docs/Installing?id=_7-update-mainapplicationjava).

**Comment by wumke** [comment]
Thanks for entering the issue, I will check which version I have for the cli... as far as I remember I linked it via 'react-native link' in the last project I've used it in.

**Comment by wumke** [comment]
A quick search lead me to https://github.com/react-native-community/react-native-maps/issues/1192 with solution https://github.com/react-native-community/react-native-maps/pull/1200/commits/4b465dbcf5bb87cf7e3ecc8f08a4acec609d32c0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 If you add this locally to the package.json, does it link automatically then?

**Comment by pmyagkov** [comment]
It would be very nice to add a podspec describing the package since react-native 0.60.* has moved to this kind of packages distributing and linking.
