### ISSUE TITLE
react native link is not working IOS

### ISSUE THREAD

**Issue by huydq580** [wumke/react-native-exit-app#30]
An error happened while build IOS
![Screen Shot 2019-08-01 at 11 23 22 AM](https://user-images.githubusercontent.com/32006273/62265583-d249a000-b44e-11e9-8740-d7e282abe558.png)

**Comment by huydq580** [comment]
@wumke

**Comment by wumke** [comment]
Duplicate of https://github.com/wumke/react-native-exit-app/issues/29 ?

**Comment by hieuuet** [comment]
I have problems with  IOS.

**Comment by huydq580** [comment]
I have problems with ios.(version 0.60.3)

**Comment by pmyagkov** [comment]
> Duplicate of #29 ?

No.

It would be very nice to add a `podspec` describing the package since react-native 0.60.* has moved to this kind of packages distributing and linking.

**Comment by wumke** [comment]
Feel free to send a pull request, I'm to busy at the moment. :-(

The RN team seems to like to mess things up in new releases...

**Comment by wumke** [comment]
podspec is added so should work now
