### ISSUE TITLE
Release a new npm version

### ISSUE THREAD

**Issue by Maders** [wumke/react-native-exit-app#33]
Hey.
Would you consider releasing a new version to npm? We really need #25 in our app.
Thanks

**Comment by julioxavierr** [comment]
I think we do have it, the changes on https://github.com/wumke/react-native-exit-app/pull/25 were merged on Jul 1 and a new version was released on Sep 11. Are you using v1.1.0?

**Comment by julioxavierr** [comment]
Just installed on a project to make sure, it's done.
@wumke can we close this issue?
