### ISSUE TITLE
Issue exiting app with iOS

### ISSUE THREAD

**Issue by LeThanhAn** [wumke/react-native-exit-app#34]
Version used: `"react-native-exit-app": "^1.1.0"`

Installation method: 
`yarn add react-native-exit-app
react-native link react-native-exit-app`

Error faced: `null is not an object (Evaluating' _reactNative.NativeModules.RNExitApp.exitApp')`

EDIT: Issue was resolved by manually linking the package. Maybe something could be done with `react-native link react-native-exit-app`

**Comment by wumke** [comment]
It seems that in some versions linking goes wrong indeed, but... after rn60 there is autolinking so for all users that stumble upon this issue: please link it manually for a little while.
