### ISSUE TITLE
RNExitApp.exitApp() issue on Android

### ISSUE THREAD

**Issue by smalbois-panoptio** [wumke/react-native-exit-app#37]
Followed the instructions:

```
import RNExitApp from 'react-native-exit-app';
```
and calling 
```
RNExitApp.exitApp()
```
This works well on IOS but not on Android. I am using jetify

Linked:
```
info iOS module "react-native-exit-app" is already linked
info Android module "react-native-exit-app" is already linked
```

"react-native-exit-app": "^1.1.0",

Getting 
```
11-22 15:57:23.683 12470 12522 W ReactNativeJS: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNExitApp.exitApp')
```

**Comment by smalbois-panoptio** [comment]
I also checked the manual steps for linking and cannot see any issues there.

**Comment by wumke** [comment]
Hmmm, the ''null is not an object (evaluating package.function" error's I've encountered in different packages always were issues with linking. 

Can you try the general stuff like clean project, rebuild, restart android studio... I've seen a lot of strange stuff and often it was not really the code that was the issue but some caches that were not updated. (same for Xcode...)

**Comment by kbanashek** [comment]
I'm seeing the same exception occur on iOS, however it works fine on android.

**Comment by mthuong** [comment]
> I'm seeing the same exception occur on iOS, however it works fine on android.
> 
> ![image](https://user-images.githubusercontent.com/2280402/71732546-893eb300-2e15-11ea-90f3-99aa2e10eb2a.png)

Did you run `pod install`? @kbanashek

**Comment by CarliBotes** [comment]
I'm getting this same error on iOS
- Ran pod install
- Reinstalled all modules
- Cleared caches
- Restarted Xcode, simulator and metro

**Comment by wumke** [comment]
For the iOS issue: which versions of RN do you guys use?
See https://github.com/wumke/react-native-exit-app/pull/31

npm version might not be up to date with latest changes on master branch... did you try master branch?
(I'm very busy with a huge PHP project at the moment so no time to check or update my RN libs...)

**Comment by kbanashek** [comment]
@wumke I ran the same commands as well.

RN version is 61

**Comment by akudahewa** [comment]
I also tried with Android. same issue comes TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNExitApp.exitApp')

I did restart,cache clear so on.. nothing happen . same error. Any idea ?

**Comment by makarkotlov** [comment]
same here on Android RN 63 react-native-exit-app 1.1.0

**Comment by 452MJ** [comment]
> same here on Android RN 63 react-native-exit-app 1.1.0

It work fine for me with RN0.63.2

**Comment by jasmeet447** [comment]
I got the same issue while using it on tvos, I am working on a Renaative project with version 0.28.18. tried everything such as pod install, cleaned build folder, and derived data. Can I get some help?

**Comment by wumke** [comment]
The linking process may not be compatible with older, or latest RN releases... sadly RN versioning makes it extremely hard to maintain easy compatability for third party lib owners!
