### ISSUE TITLE
Remove createJSmodules, it fails 0.47+ react builds

### ISSUE THREAD

**Issue by sneerin** [wumke/react-native-exit-app#4]
Remove createJSmodules, it fails 0.47+ react builds, 
Users/mdomarev/workspace/elmy-react-native/node_modules/react-native-exit-app/android/src/main/java/com/github/wumke/RNExitApp/RNExitAppPackage.java:26: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

**Comment by wumke** [comment]
fixed in 1.0.0
