### ISSUE TITLE
null is not an object ( evaluating 'reactNative.NativeModules.RNExitApp.exitApp')

### ISSUE THREAD

**Issue by hanaechahid** [wumke/react-native-exit-app#42]
hi,

after I have been installed react native exit app on my project, when I want to exit my app by clicking exit button I get this error: 
```null is not an object ( evaluating 'reactNative.NativeModules.RNExitApp.exitApp')```
thanks
"react": "16.8.3",
"react-native": "0.59.0",
"react-native-exit-app": "^1.1.0"

**Comment by PanduAluvala** [comment]
how did you solve this issue ?? any solutions . Thanks

**Comment by HarpalSingh7395** [comment]
@PanduAluvala just run `pod install `in the ios folder in your project and then rebuild your project.
