### ISSUE TITLE
Android closing the application while in background

### ISSUE THREAD

**Issue by IgorMitev** [wumke/react-native-exit-app#44]
The implementation works well when the application is active / in foreground, but invoking RNExitApp.exitApp() while the application is in background does not remove it from Recent Apps even though android:autoRemoveFromRecents="true" in AndroidManifest.xml is configured.

Is there a way to deal with this issue?

Thank you!

**Comment by bryce0516** [comment]
same issue

**Comment by ravinhwg** [comment]
Same issue

**Comment by ilenin** [comment]
I needed to add System.exit(0) in the package to close applications in background. 

In AndroidManifest.XML, add: 

android:noHistory="true" 
android:autoRemoveFromRecents="true"
android:excludeFromRecents="true"

@ReactMethod
public void exitApp() {
  android.os.Process.killProcess(android.os.Process.myPid());
  System.exit(0);
}

**Comment by wumke** [comment]
see https://github.com/wumke/react-native-exit-app/issues/52
Please also check that the 'exit' does not have undesired side effects...
