### ISSUE TITLE
what's the .a file in ios config

### ISSUE THREAD

**Issue by CrystalLiu123** [wumke/react-native-exit-app#46]
iOS
Add RNExitApp.xcoderproj into your project in the Libraries folder.
Add the .a file on the General tab of your target under Linked Frameworks And Libraries
Add the .a file on the Build Phases tab of your target under Link Binary With Libraries

**Comment by tarikcaliskan** [comment]
After you do react-native-link or pod install, check your project workspace.

Go to `General -> Frameworks, Libraries, and Embedded Content` and, click the `+` button. Then add the .a file inside `Workspace -> RNExitApp `.


![Screenshot 2021-03-20 at 19 07 09](https://user-images.githubusercontent.com/29506704/111876583-69f75b80-89b0-11eb-8335-c2ad03138e65.png)


![Screenshot 2021-03-20 at 19 07 22](https://user-images.githubusercontent.com/29506704/111876582-68c62e80-89b0-11eb-98d1-e965004fc201.png)

**Comment by wumke** [comment]
This is how additional compiled libraries are bundles with your XCode project
