### ISSUE TITLE
does it work on expo?

### ISSUE THREAD

**Issue by AnasAlamin** [wumke/react-native-exit-app#47]
i need to to kill the app at certain cases, and i'm using expo.
does this work on expo?

**Comment by wumke** [comment]
I never work with expo, I always 'eject'. so no idea how to integrate with expo... if anyone has info please share!

**Comment by SConaway** [comment]
If you're still looking, this package is incompatible with the fully-managed expo workflow as it relies on native code. 

However, if your goal is to have the user re-launch the app anyway, you can try using the `reloadAsync()` method from `expo-updates`: https://docs.expo.io/versions/v42.0.0/sdk/updates/#updatesreloadasync
