### ISSUE TITLE
Release a new npm version

### ISSUE THREAD

**Issue by sachitram-cv** [wumke/react-native-exit-app#57]
Greatly appreciate if a new npm version can be released.

**Comment by williamliangwl** [comment]
upvoting this one
cc @wumke

**Comment by vTrip** [comment]
Yep +1 to this. Release new npm version.

Cheers

**Comment by RickyL2** [comment]
+1

**Comment by tyhudson** [comment]
Does this package even work in 0.71.+?

**Comment by wumke** [comment]
v2 with new architecture support will be released...
