### ISSUE TITLE
[ANDROID] How to exit the app with animation

### ISSUE THREAD

**Issue by tikkichan4** [wumke/react-native-exit-app#6]
I just used the same android device to test my app and other apps.

My App: The quit app functionality is worked but without animation. 
Other apps: Most of apps can be closed with animation.

**Comment by wumke** [comment]
Indeed, this package does not handle any kind of animation while exiting. (Also no plans on implementing this)
If you want a custom animation before exiting you can implement it yourself in your app and then call the package kill function.

**Comment by tikkichan4** [comment]
No. I mean the default exit app animation is disappeared when using react-native-exit-app.
The function is worked but the effect just like the app is crashed.
