### ISSUE TITLE
Can u update npm?

### ISSUE THREAD

**Issue by kr-yeon** [wumke/react-native-exit-app#64]
i saw the package update. lol
can u update npm and yarn?

**Comment by wumke** [comment]
v2 with new architecture support will be updated

**Comment by kr-yeon** [comment]
yeah i need yarn publish ToT :)

**Comment by wumke** [comment]
NPM update is coming... Patience you must have, my young Padawan! ;-)
(I first need to look up my NPM password when I get home...)

**Comment by wumke** [comment]
... and having troubles with 2FA on my NPM account, so might take some days to finish my account recovery request :-( .

**Comment by wumke** [comment]
v2.0.0 now available on NPM!
