### ISSUE TITLE
Flashback when deploy app to iOS

### ISSUE THREAD

**Issue by nyngwang** [wumke/react-native-exit-app#7]
App deployed on iPhone flashbacks immediately after using this library...
How to solve this problem?
While deploying to Android works fine.

**Comment by nyngwang** [comment]
Now I'm testing on ios simulator and got `Application M has not been registered` error ...?

**Comment by nyngwang** [comment]
Oh i've solved this problem by checking AppDelegate.m 's
`RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyProjectName"`

After correcting the "MyProjectName" my problem is solved.
I didn't remember i ever change this file... but anyway if anyone came across problem with flashback hope this helps...

**Comment by wumke** [comment]
This react-native development issue can be found easily by searching google and/or stackoverflow.
