### ISSUE TITLE
error: no such file or directory: libRNExitApp.a

### ISSUE THREAD

**Issue by DorianMazur** [wumke/react-native-exit-app#73]
When I try to build and app with export type `appstore`, it's failing with this error:

clang: error: no such file or directory: '/Users/dorianmazur/Library/Developer/Xcode/DerivedData/HSEHealth-dfpjysdkkzjanwawxbicvhdzbohw/Build/Intermediates.noindex/ArchiveIntermediates/HSEHealth/BuildProductsPath/Release-appletvos/libRNExitApp.a'

**Comment by akruz97** [comment]
> When I try to build and app with export type `appstore`, it's failing with this error:
> 
> clang: error: no such file or directory: '/Users/dorianmazur/Library/Developer/Xcode/DerivedData/HSEHealth-dfpjysdkkzjanwawxbicvhdzbohw/Build/Intermediates.noindex/ArchiveIntermediates/HSEHealth/BuildProductsPath/Release-appletvos/libRNExitApp.a'

How were you able to solve it?

**Comment by DorianMazur** [comment]
We removed this package

**Comment by Treetospons** [comment]
This is work for me.

1. Before running pod install, set RCT_NEW_ARCH_ENABLED=1
example: `RCT_NEW_ARCH_ENABLED=1 pod install`
2. Modify `RNExitApp.mm` Open this file: [my-project]/node_modules/react-native-exit-app/ios/RNExitApp/RNExitApp.mm
Replace the import statement: `#import <React-Codegen/RNExitAppSpec/RNExitAppSpec.h>` to `#import <ReactCodegen/RNExitAppSpec/RNExitAppSpec.h>`
3. Modify RNExitApp.h Open this file: [my-project]/node_modules/react-native-exit-app/ios/RNExitApp/RNExitApp.h
Replace the import statement: `#import <RNExitAppSpec/RNExitAppSpec.h>` to `#import <ReactCodegen/RNExitAppSpec/RNExitAppSpec.h>`

**Comment by VimukthiShohan** [comment]
> We removed this package

@DorianMazur  What is your alternative solution?
